name: portfolio
recipe: lamp
config:
  php: '8.4'
  via: apache
  webroot: ./public
  database: postgres
  cache: redis
  xdebug: true
services:
  appserver:
    scanner:
      okCodes:
        - 401
      path: /admin/login
    build_as_root:
      # Note that you will want to use the script for the major version of node you want to install
      # See: https://github.com/nodesource/distributions/blob/master/README.md#installation-instructions
      - curl -sL https://deb.nodesource.com/setup_24.x | bash -
      - apt-get install -y nodejs
      - npm i
  database:
    portforward: 23507
tooling:
  npm:
    service: appserver
    cmd:
      - npm
  test:
    service: appserver
    cmd:
      - ./vendor/bin/phpunit --testdox
  test-coverage-html:
    service: appserver
    cmd:
      - XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-html=storage/app/coverage
  php:
    service: appserver
  phpunit:
    service: appserver
    cmd:
      - XDEBUG_MODE=coverage ./vendor/bin/phpunit
  pint:
    service: appserver
    cmd:
      - ./vendor/bin/pint
  larastan:
    service: appserver
    cmd:
      - ./vendor/bin/phpstan analyze --memory-limit=2G