name: Run linters and code formatters

on:
  workflow_call:

jobs:
  laravel-pint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}
      - name: Setup
        uses: ./.github/actions/setup
        with:
          php-version: '8.2'
          php-extensions: 'json, dom, curl, libxml, mbstring'
      - name: Install Laravel Pint
        run: composer global require laravel/pint
      - name: Run Pint
        run: pint --test
  larastan:
    name: "Larastan"
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: false
          MYSQL_ROOT_USER: lamp
          MYSQL_ROOT_PASSWORD: lamp
          MYSQL_DATABASE: lamp
        ports:
          - 3306/tcp
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
    steps:
      - name: Checkout Code
        uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}
      - name: Setup
        uses: ./.github/actions/setup
        with:
          php-version: '8.2'
      - name: Start mysql service
        run: sudo systemctl start mysql
      - name: Install Project Dependencies
        run: composer install -q --no-interaction --no-progress
      - name: Copy Environment File
        run: cp .env.example .env
      - name: Generate Application Key
        run: php artisan key:generate
      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"
      - name: Run Larastan
        run:  vendor/bin/phpstan analyze --memory-limit=2G
        env:
          DB_PORT_TEST: ${{ job.services.mysql.ports['3306'] }}
          DB_DATABASE_TEST: lamp
          DB_USERNAME_TEST: lamp
          DB_PASSWORD_TEST: lamp
