name: PR

on:
  pull_request:

jobs:
  lint:
    name: "Pint and Larastan"
    uses: ./.github/workflows/pint_larastan.yml
    secrets: inherit
  rector:
    name: "Rector"
    uses: ./.github/workflows/rector.yml
    secrets: inherit
  tests:
    name: "Tests"
    uses: ./.github/workflows/tests.yml
    secrets: inherit
  frontend:
    name: "Front end"
    uses: ./.github/workflows/frontend.yml
    secrets: inherit
