name: Run tests

on:
  workflow_call:

jobs:
  pest:
    name: "Pest"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v7
        with:
          ref: ${{ github.head_ref }}
      - name: Setup
        uses: ./.github/actions/setup
        with:
          php-version: '8.5'
      - name: Install Project Dependencies
        run: composer install -q --no-interaction --no-progress
      - name: Run Pest
        run: vendor/bin/pest --parallel
